### ISSUE TITLE
Where can I download the appropriate SANN software?

### ISSUE THREAD

**Issue by taustinn11** [LiangQiaoGu/MIonSite#2]
Hi. I was going through the README with my colleague to install and use MIonSite, but the link provided to download the SANN software is not functional.  Link: http://lee.kias.re.kr/~protein/wiki/doku.php?id=sann:download:sann

I managed to explore the lee.kias.re.kr site a little bit, but I cannot find a way to install any software. Do you know of another place to download SANN? I'm not 100% what I'm looking for.

Thanks for your time!

**Comment by xuan1376** [comment]
Hi.I have the same problem as you.Did you find a usable SANN url?

Looking forward to hearing from you!

**Comment by taustinn11** [comment]
I did not, and I am no longer looking for that software. Sorry :/

Best of luck!
